version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - CLIENT_ORIGIN=http://localhost:5173
      - SQLITE_FILE=./tictactoe.db
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_SOCKET_URL=http://localhost:3001
    depends_on:
      - server
    networks:
      - app-network
 